pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  version: '0.2.1'
  repository: "wk-j/azure-release"

steps:

- task: CacheBeta@0
  displayName: CacheBeta
  inputs:
    key: 'package-lock.json'
    path: 'node_modules'
    cacheHitVar: npmCache

- script: |
    npm install