pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'
  version: '0.2.1'
  repository: "wk-j/azure-release"

steps:

- task: CacheBeta@0
  displayName: CacheBeta
  inputs:
    key: 'package-lock.json'
    path: '$(Build.SourcesDirectory)/node_modules'
    cacheHitVar: npmCache

- task: CacheBeta@0
  displayName: 'CacheBeta (NuGet)'
  inputs:
    key: tests/MyWeb.Tests/MyWeb.Tests.csproj
    path: '$(Pipeline.Workspace)/.nuget/packages'
    cacheHitVar: 'package_cache_hit'

- script: |
    npm install
  displayName: 'Npm install'

- script: |
    dotnet test tests/MyWeb.Tests/MyWeb.Tests.csproj
  displayName: '.NET tests'