pool:
  vmImage: 'Ubuntu 16.04'

variables:
  globalPackagesFolder: './pacakge'

steps:

- script: |
     dotnet nuget locals --list global-packages
     nuget config -set globalPackagesFolder=$(globalPackagesFolder) -configfile NuGet.Config
  displayName: 'Change global package path'

- task: CacheBeta@0
  displayName: 'Cache package-lock.json'
  inputs:
    key: 'package-lock.json'
    path: '$(Build.SourcesDirectory)/node_modules'
    cacheHitVar: npmCache

- task: CacheBeta@0
  displayName: 'Cache nuget packages'
  inputs:
    key: MyWeb.Tests.csproj
    path: '$(Build.SourcesDirectory)/$(globalPackagesFolder)'
    cacheHitVar: nugetCache

- script: |
    npm install
  displayName: 'Npm install'

- script: |
    dotnet test tests/MyWeb.Tests/MyWeb.Tests.csproj
  displayName: '.NET tests'